### ISSUE TITLE
ffmpeg options

### ISSUE THREAD

**Issue by luchmhor** [Bleuzen/SpotRec#2]
Hi, first of all thanks for this gem.

Would it be possible to select output options of ffmpeg, or even simpler just a general selection of the output quality. e.g. for Audiobooks the quality could be mp3/96, not neccessary to have flac.

Cheers.

**Comment by Bleuzen** [comment]
Hi,
sure it would be possible, but useless, because we have a problem right now.

SpotRec records some time longer at the end to be sure that nothing is missing at the end.
(There is currently no better way to do that, because I can't get the exact start and ending of a song.)
But sometimes within this time, the next song already starts. So the end of the song before also contains the first second or somewhat of the next song.
That's why I recommend to post-process the audio files with Audacity (see the Hints in the Readme).

And since you have to use Audacity anyway to cut the audio to what you want, you can export it from there to any format you like.

So I chose a lossless format (flac) to not loose quality when reencoding, so that the user can decide later in other tools (for example Audacity) which format to export to.

By the way, if your player supports it, I recommend ogg vorbis, since this is the format which Spotify uses.
When converting formats to another (ogg -> mp3) you always lose even more quality. So it would be smart to use ogg too.

Hope that helped ;)
Bye

**Comment by judd1** [comment]
Hello and thanks for your references.
If spotify uses Vorbis, but not all players use it, so Audacity is
difficult to use, I do not understand it, I'm from the era of CD / DVD, but
I'll keep trying.
The songs are recorded perfectly with SpotRec but with K3b and tried to
convert the tracks to burn them on a CD and when I finish recording,
nothing is heard, but the way is good.
Regards.-


2018-06-19 4:29 GMT-03:00 Elias <notifications@github.com>:

**Comment by Bleuzen** [comment]
Hello
Audacity has nothing to do with vorbis directly. You can import the flac into Audacity and export it from there to mp3 or ogg vorbis for example, but also a lot more.
Audacity is pretty easy to use. Just mark the area to remove and press Ctrl + X.

Hm, maybe K3b has a problem with it's flac decoder (if I understood you right).. try something else like ogg, it should work with K3b.

**Comment by Bleuzen** [comment]
Closed because there was no answer for some time.
Feel free to reopen or open a PR if you have an idea to cut the audio files exactly.
