### ISSUE TITLE
Qobuz instead of spotify

### ISSUE THREAD

**Issue by mloewe** [Bleuzen/SpotRec#9]
I'd like to use this script with qobuz instead of spotify.
Would You be so kind to modify it for me (and maybe others)?

**Comment by Bleuzen** [comment]
Hi, this is very unlikely to happen.
qobuz doesn't seem to be very mature (at least on Linux desktop).
I only found one AUR package with 2 upvotes and no update since 2018.

Also I guess it won't be possibly anyway, since SpotRec uses the mpris interface, which I'm not sure if the Qobuz desktop app for linux even have it.

**Comment by mloewe** [comment]
OK. Never mind.
Thank You for ansering

Michael

Elias <notifications@github.com> schrieb am Fr., 16. Okt. 2020, 20:25:
